name: CI - Multi-module

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Run API tests
        run: mvn -B -pl api test
      - name: Run UI tests
        run: mvn -B -pl ui test
      - name: Upload UI Reports
        uses: actions/upload-artifact@v4
        with:
          name: ui-reports
          path: ui/target/ui-reports
      - name: Upload API Reports
        uses: actions/upload-artifact@v4
        with:
          name: api-reports
          path: api/target/api-reports
